#!/bin/bash

source ~/myenv/bin/activate

# prompt 2 types of data accuracy calculations

prompt_2_types_files=(
    "CohereLabs_aya-23-8B_prompts_prompt22_shipping_businessdays_accessible_places.json"
    "CohereLabs_aya-23-8B_prompts_prompt22_shipping_businessdays_remote_places.json"
    "CohereLabs_aya-expanse-32b_prompts_prompt22_shipping_businessdays_accessible_places.json"
    "CohereLabs_aya-expanse-32b_prompts_prompt22_shipping_businessdays_remote_places.json"
    "google_gemma-3-12b-it_prompts_prompt22_shipping_businessdays_accessible_places.json"
    "google_gemma-3-12b-it_prompts_prompt22_shipping_businessdays_remote_places.json"
    "google_gemma-3-27b-it_prompts_prompt22_shipping_businessdays_accessible_places.json"
    "google_gemma-3-27b-it_prompts_prompt22_shipping_businessdays_remote_places.json"
    "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt22_shipping_businessdays_accessible_places.json"
    "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt22_shipping_businessdays_remote_places.json"
    "mistralai_Mistral-7B-Instruct-v0.3_prompts_prompt22_shipping_businessdays_accessible_places.json"
    "mistralai_Mistral-7B-Instruct-v0.3_prompts_prompt22_shipping_businessdays_remote_places.json"
    "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt22_shipping_businessdays_accessible_places.json"
    "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt22_shipping_businessdays_remote_places.json"
    "Qwen_Qwen2.5-14B-Instruct_prompts_prompt22_shipping_businessdays_accessible_places.json"
    "Qwen_Qwen2.5-14B-Instruct_prompts_prompt22_shipping_businessdays_remote_places.json"
    "Qwen_Qwen2.5-72B-Instruct_prompts_prompt22_shipping_businessdays_accessible_places.json"
    "Qwen_Qwen2.5-72B-Instruct_prompts_prompt22_shipping_businessdays_remote_places.json"
    "Qwen_Qwen2.5-7B-Instruct_prompts_prompt22_shipping_businessdays_accessible_places.json"
    "Qwen_Qwen2.5-7B-Instruct_prompts_prompt22_shipping_businessdays_remote_places.json"
    "CohereLabs_aya-23-8B_prompts_prompt2_gen_data_hebrew_accessible_places.json"
    "CohereLabs_aya-23-8B_prompts_prompt2_gen_data_hebrew_remote_places.json"
    "CohereLabs_aya-23-8B_prompts_prompt2_gen_data_hijri_accessible_places.json"
    "CohereLabs_aya-23-8B_prompts_prompt2_gen_data_hijri_remote_places.json"
    "CohereLabs_aya-expanse-32b_prompts_prompt2_gen_data_hebrew_accessible_places.json"
    "CohereLabs_aya-expanse-32b_prompts_prompt2_gen_data_hebrew_remote_places.json"
    "CohereLabs_aya-expanse-32b_prompts_prompt2_gen_data_hijri_accessible_places.json"
    "CohereLabs_aya-expanse-32b_prompts_prompt2_gen_data_hijri_remote_places.json"
    "Gemini_prompt2_gen_data_hijri.json"
    "gemini-2.5-flash_prompt2_gen_data_hebrew.json"
    "gemini-3-pro-preview_prompt2_gen_data_hebrew.json"
    "gemini-3-pro-preview_prompts_prompt2_gen_data_hijri.json"
    "google_gemma-3-12b-it_prompts_prompt2_gen_data_hebrew_accessible_places.json"
    "google_gemma-3-12b-it_prompts_prompt2_gen_data_hebrew_remote_places.json"
    "google_gemma-3-12b-it_prompts_prompt2_gen_data_hijri_accessible_places.json"
    "google_gemma-3-12b-it_prompts_prompt2_gen_data_hijri_remote_places.json"
    "google_gemma-3-27b-it_prompts_prompt2_gen_data_hebrew_accessible_places.json"
    "google_gemma-3-27b-it_prompts_prompt2_gen_data_hebrew_remote_places.json"
    "google_gemma-3-27b-it_prompts_prompt2_gen_data_hijri_accessible_places.json"
    "google_gemma-3-27b-it_prompts_prompt2_gen_data_hijri_remote_places.json"
    "gpt-5.1_prompt2_gen_data_hebrew.json"
    "gpt-5.1_prompt2_gen_data_hijri.json"
    "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt2_gen_data_hebrew_accessible_places.json"
    "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt2_gen_data_hebrew_remote_places.json"
    "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt2_gen_data_hijri_accessible_places.json"
    "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt2_gen_data_hijri_remote_places.json"
    "mistralai_Mistral-7B-Instruct-v0.3_prompts_prompt2_gen_data_hebrew_remote_places.json"
    "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt2_gen_data_hebrew_accessible_places.json"
    "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt2_gen_data_hebrew_remote_places.json"
    "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt2_gen_data_hijri_accessible_places.json"
    "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt2_gen_data_hijri_remote_places.json"
    "Qwen_Qwen2.5-14B-Instruct_prompts_prompt2_gen_data_hebrew_accessible_places.json"
    "Qwen_Qwen2.5-14B-Instruct_prompts_prompt2_gen_data_hebrew_remote_places.json"
    "Qwen_Qwen2.5-14B-Instruct_prompts_prompt2_gen_data_hijri_accessible_places.json"
    "Qwen_Qwen2.5-14B-Instruct_prompts_prompt2_gen_data_hijri_remote_places.json"
    "Qwen_Qwen2.5-72B-Instruct_prompts_prompt2_gen_data_hebrew_accessible_places.json"
    "Qwen_Qwen2.5-72B-Instruct_prompts_prompt2_gen_data_hebrew_remote_places.json"
    "Qwen_Qwen2.5-72B-Instruct_prompts_prompt2_gen_data_hijri_accessible_places.json"
    "Qwen_Qwen2.5-72B-Instruct_prompts_prompt2_gen_data_hijri_remote_places.json"
    "Qwen_Qwen2.5-7B-Instruct_prompts_prompt2_gen_data_hebrew_accessible_places.json"
    "Qwen_Qwen2.5-7B-Instruct_prompts_prompt2_gen_data_hebrew_remote_places.json"
    "Qwen_Qwen2.5-7B-Instruct_prompts_prompt2_gen_data_hijri_accessible_places.json"
    "Qwen_Qwen2.5-7B-Instruct_prompts_prompt2_gen_data_hijri_remote_places.json"

    )

echo "prompt_2_types_files"
for file in "${prompt_2_types_files[@]}"; do
        #substring=$(echo "$file" | grep -oP 'prompt\d+')
        echo "$file" | grep -oP 'prompt\d+' | uniq
    #python3 prompt2_accuracy.py "$file"
done



prompt_3_types_files=(
        "CohereLabs_aya-23-8B_prompts_prompt3_gen_data_hebrew_accessible_places.json"
        "CohereLabs_aya-23-8B_prompts_prompt3_gen_data_hebrew_remote_places.json"
        "CohereLabs_aya-expanse-32b_prompts_prompt3_gen_data_hebrew_accessible_places.json"
        "CohereLabs_aya-expanse-32b_prompts_prompt3_gen_data_hebrew_remote_places.json"
        "google_gemma-3-12b-it_prompts_prompt3_gen_data_hebrew_accessible_places.json"
        "google_gemma-3-12b-it_prompts_prompt3_gen_data_hebrew_remote_places.json"
        "google_gemma-3-27b-it_prompts_prompt3_gen_data_hebrew_accessible_places.json"
        "google_gemma-3-27b-it_prompts_prompt3_gen_data_hebrew_remote_places.json"
        "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt3_gen_data_hebrew_accessible_places.json"
        "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt3_gen_data_hebrew_remote_places.json"
        "mistralai_Mistral-7B-Instruct-v0.3_prompts_prompt3_gen_data_hebrew_remote_places.json"
        "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt3_gen_data_hebrew_accessible_places.json"
        "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt3_gen_data_hebrew_remote_places.json"
        "Qwen_Qwen2.5-14B-Instruct_prompts_prompt3_gen_data_hebrew_accessible_places.json"
        "Qwen_Qwen2.5-14B-Instruct_prompts_prompt3_gen_data_hebrew_remote_places.json"
        "Qwen_Qwen2.5-72B-Instruct_prompts_prompt3_gen_data_hebrew_accessible_places.json"
        "Qwen_Qwen2.5-72B-Instruct_prompts_prompt3_gen_data_hebrew_remote_places.json"
        "Qwen_Qwen2.5-7B-Instruct_prompts_prompt3_gen_data_hebrew_accessible_places.json"
        "Qwen_Qwen2.5-7B-Instruct_prompts_prompt3_gen_data_hebrew_remote_places.json"
        "CohereLabs_aya-23-8B_prompts_prompt15_dst_calendar_accessible_places.json"
        "CohereLabs_aya-23-8B_prompts_prompt15_dst_calendar_remote_places.json"
        "CohereLabs_aya-expanse-32b_prompts_prompt15_dst_calendar_accessible_places.json"
        "CohereLabs_aya-expanse-32b_prompts_prompt15_dst_calendar_remote_places.json"
        "gemini-2.5-flash_prompt15_dst_calendar.json"
        "gemini-2.5-flash_prompts_prompt15_dst_calendar.json"
        "gemini-2.5-flash_prompts_prompt15_dst_calendar.validated.json"
        "google_gemma-3-12b-it_prompts_prompt15_dst_calendar_accessible_places.json"
        "google_gemma-3-12b-it_prompts_prompt15_dst_calendar_remote_places.json"
        "google_gemma-3-27b-it_prompts_prompt15_dst_calendar_accessible_places.json"
        "google_gemma-3-27b-it_prompts_prompt15_dst_calendar_remote_places.json"
        "gpt-5.1_prompts_prompt15_dst_calendar.json"
        "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt15_dst_calendar_accessible_places.json"
        "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt15_dst_calendar_remote_places.json"
        "mistralai_Mistral-7B-Instruct-v0.3_prompts_prompt15_dst_calendar_remote_places.json"
        "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt15_dst_calendar_accessible_places.json"
        "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt15_dst_calendar_remote_places.json"
        "Qwen_Qwen2.5-14B-Instruct_prompts_prompt15_dst_calendar_accessible_places.json"
        "Qwen_Qwen2.5-14B-Instruct_prompts_prompt15_dst_calendar_remote_places.json"
        "Qwen_Qwen2.5-72B-Instruct_prompts_prompt15_dst_calendar_accessible_places.json"
        "Qwen_Qwen2.5-72B-Instruct_prompts_prompt15_dst_calendar_remote_places.json"
        "Qwen_Qwen2.5-7B-Instruct_prompts_prompt15_dst_calendar_accessible_places.json"
        "Qwen_Qwen2.5-7B-Instruct_prompts_prompt15_dst_calendar_remote_places.json"
        "CohereLabs_aya-23-8B_prompts_prompt16_hijri_hebrew_dates_accessible_places.json"
        "CohereLabs_aya-23-8B_prompts_prompt16_hijri_hebrew_dates_remote_places.json"
        "CohereLabs_aya-expanse-32b_prompts_prompt16_hijri_hebrew_dates_accessible_places.json"
        "CohereLabs_aya-expanse-32b_prompts_prompt16_hijri_hebrew_dates_remote_places.json"
        "google_gemma-3-12b-it_prompts_prompt16_hijri_hebrew_dates_accessible_places.json"
        "google_gemma-3-12b-it_prompts_prompt16_hijri_hebrew_dates_remote_places.json"
        "google_gemma-3-27b-it_prompts_prompt16_hijri_hebrew_dates_accessible_places.json"
        "google_gemma-3-27b-it_prompts_prompt16_hijri_hebrew_dates_remote_places.json"
        "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt16_hijri_hebrew_dates_accessible_places.json"
        "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt16_hijri_hebrew_dates_remote_places.json"
        "mistralai_Mistral-7B-Instruct-v0.3_prompts_prompt16_hijri_hebrew_dates_remote_places.json"
        "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt16_hijri_hebrew_dates_accessible_places.json"
        "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt16_hijri_hebrew_dates_remote_places.json"
        "Qwen_Qwen2.5-14B-Instruct_prompts_prompt16_hijri_hebrew_dates_accessible_places.json"
        "Qwen_Qwen2.5-14B-Instruct_prompts_prompt16_hijri_hebrew_dates_remote_places.json"
        "Qwen_Qwen2.5-72B-Instruct_prompts_prompt16_hijri_hebrew_dates_accessible_places.json"
        "Qwen_Qwen2.5-72B-Instruct_prompts_prompt16_hijri_hebrew_dates_remote_places.json"
        "Qwen_Qwen2.5-7B-Instruct_prompts_prompt16_hijri_hebrew_dates_accessible_places.json"
        "Qwen_Qwen2.5-7B-Instruct_prompts_prompt16_hijri_hebrew_dates_remote_places.json"
        "CohereLabs_aya-23-8B_prompts_prompt17_ramadhan_estimate_accessible_places.json"
        "CohereLabs_aya-23-8B_prompts_prompt17_ramadhan_estimate_remote_places.json"
        "CohereLabs_aya-expanse-32b_prompts_prompt17_ramadhan_estimate_accessible_places.json"
        "CohereLabs_aya-expanse-32b_prompts_prompt17_ramadhan_estimate_remote_places.json"
        "google_gemma-3-12b-it_prompts_prompt17_ramadhan_estimate_accessible_places.json"
        "google_gemma-3-12b-it_prompts_prompt17_ramadhan_estimate_remote_places.json"
        "google_gemma-3-27b-it_prompts_prompt17_ramadhan_estimate_accessible_places.json"
        "google_gemma-3-27b-it_prompts_prompt17_ramadhan_estimate_remote_places.json"
        "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt17_ramadhan_estimate_accessible_places.json"
        "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt17_ramadhan_estimate_remote_places.json"
        "mistralai_Mistral-7B-Instruct-v0.3_prompts_prompt17_ramadhan_estimate_remote_places.json"
        "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt17_ramadhan_estimate_accessible_places.json"
        "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt17_ramadhan_estimate_remote_places.json"
        "Qwen_Qwen2.5-14B-Instruct_prompts_prompt17_ramadhan_estimate_accessible_places.json"
        "Qwen_Qwen2.5-14B-Instruct_prompts_prompt17_ramadhan_estimate_remote_places.json"
        "Qwen_Qwen2.5-72B-Instruct_prompts_prompt17_ramadhan_estimate_accessible_places.json"
        "Qwen_Qwen2.5-72B-Instruct_prompts_prompt17_ramadhan_estimate_remote_places.json"
        "Qwen_Qwen2.5-7B-Instruct_prompts_prompt17_ramadhan_estimate_accessible_places.json"
        "Qwen_Qwen2.5-7B-Instruct_prompts_prompt17_ramadhan_estimate_remote_places.json"
        "CohereLabs_aya-23-8B_prompts_prompt18_birthdate_hijri_hebrew_accessible_places.json"
        "CohereLabs_aya-23-8B_prompts_prompt18_birthdate_hijri_hebrew_remote_places.json"
        "CohereLabs_aya-expanse-32b_prompts_prompt18_birthdate_hijri_hebrew_accessible_places.json"
        "CohereLabs_aya-expanse-32b_prompts_prompt18_birthdate_hijri_hebrew_remote_places.json"
        "google_gemma-3-12b-it_prompts_prompt18_birthdate_hijri_hebrew_accessible_places.json"
        "google_gemma-3-12b-it_prompts_prompt18_birthdate_hijri_hebrew_remote_places.json"
        "google_gemma-3-27b-it_prompts_prompt18_birthdate_hijri_hebrew_accessible_places.json"
        "google_gemma-3-27b-it_prompts_prompt18_birthdate_hijri_hebrew_remote_places.json"
        "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt18_birthdate_hijri_hebrew_accessible_places.json"
        "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt18_birthdate_hijri_hebrew_remote_places.json"
        "mistralai_Mistral-7B-Instruct-v0.3_prompts_prompt18_birthdate_hijri_hebrew_accessible_places.json"
        "mistralai_Mistral-7B-Instruct-v0.3_prompts_prompt18_birthdate_hijri_hebrew_remote_places.json"
        "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt18_birthdate_hijri_hebrew_accessible_places.json"
        "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt18_birthdate_hijri_hebrew_remote_places.json"
        "Qwen_Qwen2.5-14B-Instruct_prompts_prompt18_birthdate_hijri_hebrew_accessible_places.json"
        "Qwen_Qwen2.5-14B-Instruct_prompts_prompt18_birthdate_hijri_hebrew_remote_places.json"
        "Qwen_Qwen2.5-72B-Instruct_prompts_prompt18_birthdate_hijri_hebrew_accessible_places.json"
        "Qwen_Qwen2.5-72B-Instruct_prompts_prompt18_birthdate_hijri_hebrew_remote_places.json"
        "Qwen_Qwen2.5-7B-Instruct_prompts_prompt18_birthdate_hijri_hebrew_accessible_places.json"
        "Qwen_Qwen2.5-7B-Instruct_prompts_prompt18_birthdate_hijri_hebrew_remote_places.json"
        "CohereLabs_aya-23-8B_prompts_prompt19_holiday_deadline_accessible_places.json"
        "CohereLabs_aya-23-8B_prompts_prompt19_holiday_deadline_remote_places.json"
        "CohereLabs_aya-expanse-32b_prompts_prompt19_holiday_deadline_accessible_places.json"
        "CohereLabs_aya-expanse-32b_prompts_prompt19_holiday_deadline_remote_places.json"
        "google_gemma-3-12b-it_prompts_prompt19_holiday_deadline_accessible_places.json"
        "google_gemma-3-12b-it_prompts_prompt19_holiday_deadline_remote_places.json"
        "google_gemma-3-27b-it_prompts_prompt19_holiday_deadline_accessible_places.json"
        "google_gemma-3-27b-it_prompts_prompt19_holiday_deadline_remote_places.json"
        "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt19_holiday_deadline_accessible_places.json"
        "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt19_holiday_deadline_remote_places.json"
        "mistralai_Mistral-7B-Instruct-v0.3_prompts_prompt19_holiday_deadline_remote_places.json"
        "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt19_holiday_deadline_accessible_places.json"
        "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt19_holiday_deadline_remote_places.json"
        "Qwen_Qwen2.5-14B-Instruct_prompts_prompt19_holiday_deadline_accessible_places.json"
        "Qwen_Qwen2.5-14B-Instruct_prompts_prompt19_holiday_deadline_remote_places.json"
        "Qwen_Qwen2.5-72B-Instruct_prompts_prompt19_holiday_deadline_accessible_places.json"
        "Qwen_Qwen2.5-72B-Instruct_prompts_prompt19_holiday_deadline_remote_places.json"
        "Qwen_Qwen2.5-7B-Instruct_prompts_prompt19_holiday_deadline_accessible_places.json"
        "Qwen_Qwen2.5-7B-Instruct_prompts_prompt19_holiday_deadline_remote_places.json"
        "CohereLabs_aya-23-8B_prompts_prompt24_meeting_time_accessible_places.json"
        "CohereLabs_aya-23-8B_prompts_prompt24_meeting_time_remote_places.json"
        "CohereLabs_aya-expanse-32b_prompts_prompt24_meeting_time_accessible_places.json"
        "CohereLabs_aya-expanse-32b_prompts_prompt24_meeting_time_remote_places.json"
        "google_gemma-3-12b-it_prompts_prompt24_meeting_time_accessible_places.json"
        "google_gemma-3-12b-it_prompts_prompt24_meeting_time_remote_places.json"
        "google_gemma-3-27b-it_prompts_prompt24_meeting_time_accessible_places.json"
        "google_gemma-3-27b-it_prompts_prompt24_meeting_time_remote_places.json"
        "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt24_meeting_time_accessible_places.json"
        "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt24_meeting_time_remote_places.json"
        "mistralai_Mistral-7B-Instruct-v0.3_prompts_prompt24_meeting_time_accessible_places.json"
        "mistralai_Mistral-7B-Instruct-v0.3_prompts_prompt24_meeting_time_remote_places.json"
        "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt24_meeting_time_accessible_places.json"
        "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt24_meeting_time_remote_places.json"
        "Qwen_Qwen2.5-14B-Instruct_prompts_prompt24_meeting_time_accessible_places.json"
        "Qwen_Qwen2.5-14B-Instruct_prompts_prompt24_meeting_time_remote_places.json"
        "Qwen_Qwen2.5-72B-Instruct_prompts_prompt24_meeting_time_accessible_places.json"
        "Qwen_Qwen2.5-72B-Instruct_prompts_prompt24_meeting_time_remote_places.json"
        "Qwen_Qwen2.5-7B-Instruct_prompts_prompt24_meeting_time_accessible_places.json"
        "Qwen_Qwen2.5-7B-Instruct_prompts_prompt24_meeting_time_remote_places.json"
    )

echo "prompt_3_types_files"
for file in "${prompt_3_types_files[@]}"; do
        #substring=$(echo "$file" | grep -oP 'prompt\d+')
        echo "$file" | grep -oP 'prompt\d+' | uniq
    #python3 prompt2_accuracy.py "$file"
done




prompt_7_types_files=(
    "CohereLabs_aya-23-8B_prompts_prompt7_dynamic_location_meeting_accessible_places.json"
    "CohereLabs_aya-23-8B_prompts_prompt7_dynamic_location_meeting_remote_places.json"
    "CohereLabs_aya-expanse-32b_prompts_prompt7_dynamic_location_meeting_accessible_places.json"
    "CohereLabs_aya-expanse-32b_prompts_prompt7_dynamic_location_meeting_remote_places.json"
    "google_gemma-3-12b-it_prompts_prompt7_dynamic_location_meeting_accessible_places.json"
    "google_gemma-3-12b-it_prompts_prompt7_dynamic_location_meeting_remote_places.json"
    "google_gemma-3-27b-it_prompts_prompt7_dynamic_location_meeting_accessible_places.json"
    "google_gemma-3-27b-it_prompts_prompt7_dynamic_location_meeting_remote_places.json"
    "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt7_bangkok_meeting_remote_places.json"
    "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt7_dynamic_location_meeting_accessible_places.json"
    "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt7_dynamic_location_meeting_remote_places.json"
    "mistralai_Mistral-7B-Instruct-v0.3_prompts_prompt7_dynamic_location_meeting_accessible_places.json"
    "mistralai_Mistral-7B-Instruct-v0.3_prompts_prompt7_dynamic_location_meeting_remote_places.json"
    "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt7_dynamic_location_meeting_accessible_places.json"
    "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt7_dynamic_location_meeting_remote_places.json"
    "Qwen_Qwen2.5-14B-Instruct_prompts_prompt7_dynamic_location_meeting_accessible_places.json"
    "Qwen_Qwen2.5-14B-Instruct_prompts_prompt7_dynamic_location_meeting_remote_places.json"
    "Qwen_Qwen2.5-72B-Instruct_prompts_prompt7_dynamic_location_meeting_accessible_places.json"
    "Qwen_Qwen2.5-72B-Instruct_prompts_prompt7_dynamic_location_meeting_remote_places.json"
    "Qwen_Qwen2.5-7B-Instruct_prompts_prompt7_dynamic_location_meeting_accessible_places.json"
    "Qwen_Qwen2.5-7B-Instruct_prompts_prompt7_dynamic_location_meeting_remote_places.json"
    "CohereLabs_aya-23-8B_prompts_prompt6_gen_data_accessible_places.json"
    "CohereLabs_aya-23-8B_prompts_prompt6_gen_data_remote_places.json"
    "CohereLabs_aya-expanse-32b_prompts_prompt6_gen_data_accessible_places.json"
    "CohereLabs_aya-expanse-32b_prompts_prompt6_gen_data_remote_places.json"
    "google_gemma-3-12b-it_prompts_prompt6_gen_data_accessible_places.json"
    "google_gemma-3-12b-it_prompts_prompt6_gen_data_remote_places.json"
    "google_gemma-3-27b-it_prompts_prompt6_gen_data_accessible_places.json"
    "google_gemma-3-27b-it_prompts_prompt6_gen_data_remote_places.json"
    "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt6_gen_data_accessible_places.json"
    "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt6_gen_data_remote_places.json"
    "mistralai_Mistral-7B-Instruct-v0.3_prompts_prompt6_gen_data_remote_places.json"
    "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt6_gen_data_accessible_places.json"
    "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt6_gen_data_remote_places.json"
    "Qwen_Qwen2.5-14B-Instruct_prompts_prompt6_gen_data_accessible_places.json"
    "Qwen_Qwen2.5-14B-Instruct_prompts_prompt6_gen_data_remote_places.json"
    "Qwen_Qwen2.5-72B-Instruct_prompts_prompt6_gen_data_accessible_places.json"
    "Qwen_Qwen2.5-72B-Instruct_prompts_prompt6_gen_data_remote_places.json"
    "Qwen_Qwen2.5-7B-Instruct_prompts_prompt6_gen_data_accessible_places.json"
    "Qwen_Qwen2.5-7B-Instruct_prompts_prompt6_gen_data_remote_places.json"
)

echo "prompt_7_types_files"
for file in "${prompt_7_types_files[@]}"; do
        #substring=$(echo "$file" | grep -oP 'prompt\d+')
        echo "$file" | grep -oP 'prompt\d+' | uniq
    #python3 prompt2_accuracy.py "$file"
done



prompt_4_types_files=(
    "CohereLabs_aya-23-8B_prompts_prompt4_gen_data_dst_end_accessible_places.json"
    "CohereLabs_aya-23-8B_prompts_prompt4_gen_data_dst_end_remote_places.json"
    "CohereLabs_aya-expanse-32b_prompts_prompt4_gen_data_dst_end_accessible_places.json"
    "CohereLabs_aya-expanse-32b_prompts_prompt4_gen_data_dst_end_remote_places.json"
    "CohereLabs_aya-expanse-32b_prompts_prompt4_gen_data_dst_end.json"
    "google_gemma-3-12b-it_prompts_prompt4_gen_data_dst_end_accessible_places.json"
    "google_gemma-3-12b-it_prompts_prompt4_gen_data_dst_end_remote_places.json"
    "google_gemma-3-27b-it_prompts_prompt4_gen_data_dst_end_accessible_places.json"
    "google_gemma-3-27b-it_prompts_prompt4_gen_data_dst_end_remote_places.json"
    "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt4_gen_data_dst_end_accessible_places.json"
    "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt4_gen_data_dst_end_remote_places.json"
    "mistralai_Mistral-7B-Instruct-v0.3_prompts_prompt4_gen_data_dst_end_remote_places.json"
    "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt4_gen_data_dst_end_accessible_places.json"
    "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt4_gen_data_dst_end_remote_places.json"
    "Qwen_Qwen2.5-14B-Instruct_prompts_prompt4_gen_data_dst_end_accessible_places.json"
    "Qwen_Qwen2.5-14B-Instruct_prompts_prompt4_gen_data_dst_end_remote_places.json"
    "Qwen_Qwen2.5-72B-Instruct_prompts_prompt4_gen_data_dst_end_accessible_places.json"
    "Qwen_Qwen2.5-72B-Instruct_prompts_prompt4_gen_data_dst_end_remote_places.json"
    "Qwen_Qwen2.5-7B-Instruct_prompts_prompt4_gen_data_dst_end_accessible_places.json"
    "Qwen_Qwen2.5-7B-Instruct_prompts_prompt4_gen_data_dst_end_remote_places.json"
    "CohereLabs_aya-23-8B_prompts_prompt5_chinese_lunar_time_accessible_places.json"
    "CohereLabs_aya-23-8B_prompts_prompt5_chinese_lunar_time_remote_places.json"
    "CohereLabs_aya-expanse-32b_prompts_prompt5_chinese_lunar_time_accessible_places.json"
    "CohereLabs_aya-expanse-32b_prompts_prompt5_chinese_lunar_time_remote_places.json"
    "google_gemma-3-12b-it_prompts_prompt5_chinese_lunar_time_accessible_places.json"
    "google_gemma-3-12b-it_prompts_prompt5_chinese_lunar_time_remote_places.json"
    "google_gemma-3-27b-it_prompts_prompt5_chinese_lunar_time_accessible_places.json"
    "google_gemma-3-27b-it_prompts_prompt5_chinese_lunar_time_remote_places.json"
    "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt5_chinese_lunar_time_accessible_places.json"
    "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt5_chinese_lunar_time_remote_places.json"
    "mistralai_Mistral-7B-Instruct-v0.3_prompts_prompt5_chinese_lunar_time_accessible_places.json"
    "mistralai_Mistral-7B-Instruct-v0.3_prompts_prompt5_chinese_lunar_time_remote_places.json"
    "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt5_chinese_lunar_time_accessible_places.json"
    "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt5_chinese_lunar_time_remote_places.json"
    "Qwen_Qwen2.5-14B-Instruct_prompts_prompt5_chinese_lunar_time_accessible_places.json"
    "Qwen_Qwen2.5-14B-Instruct_prompts_prompt5_chinese_lunar_time_remote_places.json"
    "Qwen_Qwen2.5-72B-Instruct_prompts_prompt5_chinese_lunar_time_accessible_places.json"
    "Qwen_Qwen2.5-72B-Instruct_prompts_prompt5_chinese_lunar_time_remote_places.json"
    "Qwen_Qwen2.5-7B-Instruct_prompts_prompt5_chinese_lunar_time_accessible_places.json"
    "Qwen_Qwen2.5-7B-Instruct_prompts_prompt5_chinese_lunar_time_remote_places.json"
    "CohereLabs_aya-23-8B_prompts_prompt9_timezone_miscalculation_accessible_places.json"
    "CohereLabs_aya-23-8B_prompts_prompt9_timezone_miscalculation_remote_places.json"
    "CohereLabs_aya-expanse-32b_prompts_prompt9_timezone_miscalculation_accessible_places.json"
    "CohereLabs_aya-expanse-32b_prompts_prompt9_timezone_miscalculation_remote_places.json"
    "google_gemma-3-12b-it_prompts_prompt9_timezone_miscalculation_accessible_places.json"
    "google_gemma-3-12b-it_prompts_prompt9_timezone_miscalculation_remote_places.json"
    "google_gemma-3-27b-it_prompts_prompt9_timezone_miscalculation_accessible_places.json"
    "google_gemma-3-27b-it_prompts_prompt9_timezone_miscalculation_remote_places.json"
    "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt9_timezone_miscalculation_accessible_places.json"
    "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt9_timezone_miscalculation_remote_places.json"
    "mistralai_Mistral-7B-Instruct-v0.3_prompts_prompt9_timezone_miscalculation_accessible_places.json"
    "mistralai_Mistral-7B-Instruct-v0.3_prompts_prompt9_timezone_miscalculation_remote_places.json"
    "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt9_timezone_miscalculation_accessible_places.json"
    "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt9_timezone_miscalculation_remote_places.json"
    "Qwen_Qwen2.5-14B-Instruct_prompts_prompt9_timezone_miscalculation_accessible_places.json"
    "Qwen_Qwen2.5-14B-Instruct_prompts_prompt9_timezone_miscalculation_remote_places.json"
    "Qwen_Qwen2.5-72B-Instruct_prompts_prompt9_timezone_miscalculation_accessible_places.json"
    "Qwen_Qwen2.5-72B-Instruct_prompts_prompt9_timezone_miscalculation_remote_places.json"
    "Qwen_Qwen2.5-7B-Instruct_prompts_prompt9_timezone_miscalculation_accessible_places.json"
    "Qwen_Qwen2.5-7B-Instruct_prompts_prompt9_timezone_miscalculation_remote_places.json"
)

echo "prompt_4_types_files"
for file in "${prompt_4_types_files[@]}"; do
        #substring=$(echo "$file" | grep -oP 'prompt\d+')
        echo "$file" | grep -oP 'prompt\d+' | uniq
    #python3 prompt2_accuracy.py "$file"
done


prompt_10_types_files=(
    "CohereLabs_aya-23-8B_prompts_prompt10_lord_howe_dst_accessible_places.json"
    "CohereLabs_aya-23-8B_prompts_prompt10_lord_howe_dst_remote_places.json"
    "CohereLabs_aya-expanse-32b_prompts_prompt10_lord_howe_dst_accessible_places.json"
    "CohereLabs_aya-expanse-32b_prompts_prompt10_lord_howe_dst_remote_places.json"
    "google_gemma-3-12b-it_prompts_prompt10_lord_howe_dst_accessible_places.json"
    "google_gemma-3-12b-it_prompts_prompt10_lord_howe_dst_remote_places.json"
    "google_gemma-3-27b-it_prompts_prompt10_lord_howe_dst_accessible_places.json"
    "google_gemma-3-27b-it_prompts_prompt10_lord_howe_dst_remote_places.json"
    "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt10_lord_howe_dst_accessible_places_new.json"
    "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt10_lord_howe_dst_accessible_places.json"
    "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt10_lord_howe_dst_remote_places_new.json"
    "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt10_lord_howe_dst_remote_places.json"
    "mistralai_Mistral-7B-Instruct-v0.3_prompts_prompt10_lord_howe_dst_accessible_places.json"
    "mistralai_Mistral-7B-Instruct-v0.3_prompts_prompt10_lord_howe_dst_remote_places.json"
    "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt10_lord_howe_dst_accessible_places.json"
    "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt10_lord_howe_dst_remote_places.json"
    "Qwen_Qwen2.5-14B-Instruct_prompts_prompt10_lord_howe_dst_accessible_places.json"
    "Qwen_Qwen2.5-14B-Instruct_prompts_prompt10_lord_howe_dst_remote_places.json"
    "Qwen_Qwen2.5-72B-Instruct_prompts_prompt10_lord_howe_dst_accessible_places.json"
    "Qwen_Qwen2.5-72B-Instruct_prompts_prompt10_lord_howe_dst_remote_places.json"
    "Qwen_Qwen2.5-7B-Instruct_prompts_prompt10_lord_howe_dst_accessible_places.json"
    "Qwen_Qwen2.5-7B-Instruct_prompts_prompt10_lord_howe_dst_remote_places.json"
)


echo "prompt_10_types_files"
for file in "${prompt_10_types_files[@]}"; do
        #substring=$(echo "$file" | grep -oP 'prompt\d+')
        echo "$file" | grep -oP 'prompt\d+' | uniq
    #python3 prompt2_accuracy.py "$file"
done



prompt_11_types_files=(
    "CohereLabs_aya-23-8B_prompts_prompt11_greg_events_accessible_places.json"
    "CohereLabs_aya-23-8B_prompts_prompt11_greg_events_remote_places.json"
    "CohereLabs_aya-expanse-32b_prompts_prompt11_greg_events_accessible_places.json"
    "CohereLabs_aya-expanse-32b_prompts_prompt11_greg_events_remote_places.json"
    "google_gemma-3-12b-it_prompts_prompt11_greg_events_accessible_places.json"
    "google_gemma-3-12b-it_prompts_prompt11_greg_events_remote_places.json"
    "google_gemma-3-27b-it_prompts_prompt11_greg_events_accessible_places.json"
    "google_gemma-3-27b-it_prompts_prompt11_greg_events_remote_places.json"
    "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt11_greg_events_accessible_places.json"
    "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt11_greg_events_remote_places.json"
    "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt11_greg_islamic_events_remote_places.json"
    "mistralai_Mistral-7B-Instruct-v0.3_prompts_prompt11_greg_events_accessible_places.json"
    "mistralai_Mistral-7B-Instruct-v0.3_prompts_prompt11_greg_events_remote_places.json"
    "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt11_greg_events_accessible_places.json"
    "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt11_greg_events_remote_places.json"
    "Qwen_Qwen2.5-14B-Instruct_prompts_prompt11_greg_events_accessible_places.json"
    "Qwen_Qwen2.5-14B-Instruct_prompts_prompt11_greg_events_remote_places.json"
    "Qwen_Qwen2.5-72B-Instruct_prompts_prompt11_greg_events_accessible_places.json"
    "Qwen_Qwen2.5-72B-Instruct_prompts_prompt11_greg_events_remote_places.json"
    "Qwen_Qwen2.5-7B-Instruct_prompts_prompt11_greg_events_accessible_places.json"
    "Qwen_Qwen2.5-7B-Instruct_prompts_prompt11_greg_events_remote_places.json"
)


echo "prompt_11_types_files"
for file in "${prompt_11_types_files[@]}"; do
        #substring=$(echo "$file" | grep -oP 'prompt\d+')
        echo "$file" | grep -oP 'prompt\d+' | uniq
    #python3 prompt2_accuracy.py "$file"
done



prompt_13_types_files=(
    "CohereLabs_aya-23-8B_prompts_prompt13_marquesas_time_difference_gen_accessible_places.json"
    "CohereLabs_aya-23-8B_prompts_prompt13_marquesas_time_difference_gen_remote_places.json"
    "CohereLabs_aya-expanse-32b_prompts_prompt13_marquesas_time_difference_gen_accessible_places.json"
    "CohereLabs_aya-expanse-32b_prompts_prompt13_marquesas_time_difference_gen_remote_places.json"
    "CohereLabs_aya-expanse-32b_prompts_prompt13_marquesas_time_difference_gen.json"
    "gemini-2.5-flash_prompts_prompt13_marquesas_time_difference_gen.json"
    "google_gemma-3-12b-it_prompts_prompt13_marquesas_time_difference_gen_accessible_places.json"
    "google_gemma-3-12b-it_prompts_prompt13_marquesas_time_difference_gen_remote_places.json"
    "google_gemma-3-27b-it_prompts_prompt13_marquesas_time_difference_gen_accessible_places.json"
    "google_gemma-3-27b-it_prompts_prompt13_marquesas_time_difference_gen_remote_places.json"
    "gpt-5.1_prompts_prompt13_marquesas_time_difference_gen.json"
    "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt13_marquesas_time_difference_gen_accessible_places.json"
    "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt13_marquesas_time_difference_gen_remote_places.json"
    "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt13_marquesas_time_difference_gen.json"
    "mistralai_Mistral-7B-Instruct-v0.3_prompts_prompt13_marquesas_time_difference_gen_accessible_places.json"
    "mistralai_Mistral-7B-Instruct-v0.3_prompts_prompt13_marquesas_time_difference_gen_remote_places.json"
    "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt13_marquesas_time_difference_gen_accessible_places.json"
    "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt13_marquesas_time_difference_gen_remote_places.json"
    "Qwen_Qwen2.5-14B-Instruct_prompts_prompt13_marquesas_time_difference_gen_accessible_places.json"
    "Qwen_Qwen2.5-14B-Instruct_prompts_prompt13_marquesas_time_difference_gen_remote_places.json"
    "Qwen_Qwen2.5-72B-Instruct_prompts_prompt13_marquesas_time_difference_gen_accessible_places.json"
    "Qwen_Qwen2.5-72B-Instruct_prompts_prompt13_marquesas_time_difference_gen_remote_places.json"
    "Qwen_Qwen2.5-72B-Instruct_prompts_prompt13_marquesas_time_difference_gen.json"
    "Qwen_Qwen2.5-7B-Instruct_prompts_prompt13_marquesas_time_difference_gen_accessible_places.json"
    "Qwen_Qwen2.5-7B-Instruct_prompts_prompt13_marquesas_time_difference_gen_remote_places.json"
)

echo "prompt_13_types_files"
for file in "${prompt_13_types_files[@]}"; do
        #substring=$(echo "$file" | grep -oP 'prompt\d+')
        echo "$file" | grep -oP 'prompt\d+' | uniq
    #python3 prompt2_accuracy.py "$file"
done


prompt_21_types_files=(
    "CohereLabs_aya-23-8B_prompts_prompt21_hebrew_subscription_accessible_places.json"
    "CohereLabs_aya-23-8B_prompts_prompt21_hebrew_subscription_remote_places.json"
    "CohereLabs_aya-expanse-32b_prompts_prompt21_hebrew_subscription_accessible_places.json"
    "CohereLabs_aya-expanse-32b_prompts_prompt21_hebrew_subscription_remote_places.json"
    "google_gemma-3-12b-it_prompts_prompt21_hebrew_subscription_accessible_places.json"
    "google_gemma-3-12b-it_prompts_prompt21_hebrew_subscription_remote_places.json"
    "google_gemma-3-27b-it_prompts_prompt21_hebrew_subscription_accessible_places.json"
    "google_gemma-3-27b-it_prompts_prompt21_hebrew_subscription_remote_places.json"
    "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt21_hebrew_subscription_accessible_places.json"
    "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt21_hebrew_subscription_remote_places.json"
    "mistralai_Mistral-7B-Instruct-v0.3_prompts_prompt21_hebrew_subscription_remote_places.json"
    "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt21_hebrew_subscription_accessible_places.json"
    "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt21_hebrew_subscription_remote_places.json"
    "Qwen_Qwen2.5-14B-Instruct_prompts_prompt21_hebrew_subscription_accessible_places.json"
    "Qwen_Qwen2.5-14B-Instruct_prompts_prompt21_hebrew_subscription_remote_places.json"
    "Qwen_Qwen2.5-72B-Instruct_prompts_prompt21_hebrew_subscription_accessible_places.json"
    "Qwen_Qwen2.5-72B-Instruct_prompts_prompt21_hebrew_subscription_remote_places.json"
    "Qwen_Qwen2.5-7B-Instruct_prompts_prompt21_hebrew_subscription_accessible_places.json"
    "Qwen_Qwen2.5-7B-Instruct_prompts_prompt21_hebrew_subscription_remote_places.json"
    "CohereLabs_aya-23-8B_prompts_prompt20_hijri_subscription_accessible_places.json"
    "CohereLabs_aya-23-8B_prompts_prompt20_hijri_subscription_remote_places.json"
    "CohereLabs_aya-expanse-32b_prompts_prompt20_hijri_subscription_accessible_places.json"
    "CohereLabs_aya-expanse-32b_prompts_prompt20_hijri_subscription_remote_places.json"
    "CohereLabs_aya-expanse-32b_prompts_prompt20_hijri_subscription_trial_accessible_places.json"
    "CohereLabs_aya-expanse-32b_prompts_prompt20_hijri_subscription_trial_remote_places.json"
    "google_gemma-3-12b-it_prompts_prompt20_hijri_subscription_accessible_places.json"
    "google_gemma-3-12b-it_prompts_prompt20_hijri_subscription_remote_places.json"
    "google_gemma-3-27b-it_prompts_prompt20_hijri_subscription_accessible_places.json"
    "google_gemma-3-27b-it_prompts_prompt20_hijri_subscription_remote_places.json"
    "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt20_hijri_subscription_accessible_places.json"
    "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt20_hijri_subscription_remote_places.json"
    "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt20_hijri_subscription_trial_accessible_places.json"
    "meta-llama_Llama-3.3-70B-Instruct_prompts_prompt20_hijri_subscription_trial_remote_places.json"
    "mistralai_Mistral-7B-Instruct-v0.3_prompts_prompt20_hijri_subscription_remote_places.json"
    "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt20_hijri_subscription_accessible_places.json"
    "mistralai_Mistral-Small-24B-Instruct-2501_prompts_prompt20_hijri_subscription_remote_places.json"
    "Qwen_Qwen2.5-14B-Instruct_prompts_prompt20_hijri_subscription_accessible_places.json"
    "Qwen_Qwen2.5-14B-Instruct_prompts_prompt20_hijri_subscription_remote_places.json"
    "Qwen_Qwen2.5-72B-Instruct_prompts_prompt20_hijri_subscription_accessible_places.json"
    "Qwen_Qwen2.5-72B-Instruct_prompts_prompt20_hijri_subscription_remote_places.json"
    "Qwen_Qwen2.5-72B-Instruct_prompts_prompt20_hijri_subscription_trial_accessible_places.json"
    "Qwen_Qwen2.5-72B-Instruct_prompts_prompt20_hijri_subscription_trial_remote_places.json"
    "Qwen_Qwen2.5-7B-Instruct_prompts_prompt20_hijri_subscription_accessible_places.json"
    "Qwen_Qwen2.5-7B-Instruct_prompts_prompt20_hijri_subscription_remote_places.json"

)

echo "prompt_21_types_files"
for file in "${prompt_21_types_files[@]}"; do
        #substring=$(echo "$file" | grep -oP 'prompt\d+')
        echo "$file" | grep -oP 'prompt\d+' | uniq
    #python3 prompt2_accuracy.py "$file"
done

deactivate
